### ISSUE TITLE
many extensions broken on latest A1111 commit with this extension

### ISSUE THREAD

**Issue by GitHub1712** [papuSpartan/stable-diffusion-webui-auto-tls-https#13]
Noticed on default latest A1111 commits if installing auto-tsl many other extensions are broken. By example I cannot get any localization working.

**Comment by papuSpartan** [comment]
> Noticed on default latest A1111 commits if installing auto-tsl many other extensions are broken. By example I cannot get any localization working.

It should break the webui completely on the latest **stable** branch because of the update to gradio.

It's possible to make it work on the dev branch if you use the tls verify option.

Sorry for the issue though. Currently there's not really a way for me as an extension dev to indicate this through the extensions index.

I should be updating things in a few days*

**Comment by papuSpartan** [comment]
You should be able to get around this issue now by passing `--disable-tls-verify` in your sdwui launch options
