### ISSUE TITLE
Issue with the access to the Host machine 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [papuSpartan/stable-diffusion-webui-auto-tls-https#4]
I recently installed this extension for HTTPS for self-signed cert, I usually run the app with --listen as I like the availability to run on any device on my network.

Before when running this way I was still able to access the interface using either localhost or the IP of the machine on the machine it was running, I'm now no longer able to access the interface on the machine that's hosting the application, either through localhost,[127.0.0.1](http://127.0.0.1/) or even the internal IP of the machine, but I am still able to access the interface from an external device using the IP address of the hosting machine.

Update Tested removing --listen from the arguments and still can not access the interface on localhost on the host machine But removing the Extention causes the localhost to work again while using --listen.

Thank you to anyone and all people able to help me with this issue!

**Comment by papuSpartan** [comment]
@TWIISTED-STUDIOS If you are on the latest commit then `--server-name` should override `--listen`. 

see pr: AUTOMATIC1111/stable-diffusion-webui#4717

> I'm now no longer able to access the interface on the machine that's hosting the application, either through localhost,[127.0.0.1](http://127.0.0.1/) or even the internal IP of the machine, but I am still able to access the interface from an external device using the IP address of the hosting machine.

It is possible for the webui to fail to setup a socket due to an invalid TLS configuration. In this case, it might be due to a mismatched certificate CN(common name) and server name.  Ex. if your certificate is for bear.com, then bear.com should be passed to `--server-name`. This is because it attempts to set up a circular connection to itself using the passed server name and certificate to ensure that everything checks out. If it doesn't, then an exception is thrown and you should not be able to connect as no socket is created.

Check the console output at startup for any exceptions and post the full output here.

**Comment by papuSpartan** [comment]
reopen if needed
