### ISSUE TITLE
is there a way to use this extension with the krita extension?

### ISSUE THREAD

**Issue by gsgoldma** [papuSpartan/stable-diffusion-webui-auto-tls-https#7]
![Screenshot 2023-01-30 120335](https://user-images.githubusercontent.com/113954966/215583261-534fd019-4406-44a6-b840-caac4d84fb1b.png)

getting this error, but I'm not sure how to get around it for Krita extension

**Comment by papuSpartan** [comment]
Just to confirm, this is the plugin you are talking about? https://github.com/sddebz/stable-diffusion-krita-plugin

The README says to use https://github.com/Interpause/auto-sd-paint-ext as it will no longer be updated.

**Comment by gsgoldma** [comment]
to confirm yes, and I've been using the bottom updated link

**Comment by papuSpartan** [comment]
> to confirm yes, and I've been using the bottom updated link

From what I've been able to tell this extension is using an entirely separate server utilizing fastapi. It would need to have an argument or mechanism for you to load a certificate or respect system trusted ones. 

Another thing I noticed is that they are encrypting the HTTP body using a XOR cipher instead of using HTTPS for some reason:  https://github.com/Interpause/auto-sd-paint-ext/blob/main/backend/app.py.
